[[plugins]]
repo = 'zchee/deoplete-go'
build = 'make'
on_ft = ['go']
depends = ['deoplete.nvim']
hook_source = '''
    let g:deoplete#sources#go#align_class = 1
    let g:deoplete#sources#go#sort_class = ['package', 'func', 'type', 'var', 'const']
    let g:deoplete#sources#go#gocode_binary = $GOPATH . '/bin/gocode'
    let g:deoplete#sources#go#cgo#sort_algo = 'priority'
    let g:deoplete#sources#go#package_dot = 0
    let g:deoplete#sources#go#pointer = 1
'''

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
build = ':GoUpdateBinaries'
hook_source = '''
  source ~/.vim/rc/plugins/go.rc.vim
'''
