[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-scripts/wombat256.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = ['iceberg.vim']
hook_add = 'source ~/.vim/rc/plugins/lightline.rc.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
let g:gitgutter_map_keys = 0
nmap [g <Plug>GitGutterPrevHunk
nmap ]g <Plug>GitGutterNextHunk
'''

[[plugins]]
repo = 'machakann/vim-sandwich'
hook_add = '''
nmap s <Nop>
xmap s <Nop>
'''

[[plugins]]
repo = 'mattn/sonictemplate-vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
set helplang=ja,en
'''

# [[plugins]]
# repo = 'urbainvaes/vim-remembrall'
# hook_add = '''
#     let g:remembrall_normal_keys = ["[", "]"]
#     let g:remembrall_window = 'topleft 30new'
#
#     nnoremap <silent> , :call remembrall#remind('n', ',')<cr>
#     nnoremap <silent> ,? :call remembrall#remind('n', ',')<cr>
#     vnoremap <silent> ? :call remembrall#remind('n', '')<cr>
# '''

# [[plugins]]
# repo = 'xolox/vim-session'
# depends = ['xolox/vim-misc']
# hook_add = '''
#     " Specific directory for save the session
#     let g:session_directory = xolox#misc#path#merge(getcwd(), '.vimsession')
#     " Auto save the session when close vim
#     let g:session_autosave = 'yes'
#     " Auto load the session when open vim
#     let g:session_autoload = 'no'
#     " Cycle for auto save minute
#     let g:session_autosave_periodic = 1
#
#     nmap <silent> <Leader>so :<C-u>OpenSession<CR>
#     nmap <silent> <Leader>ss :<C-u>OpenSession<CR>
# '''
#
# [[plugins]]
# repo = 'xolox/vim-misc'

