[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('nvim')"
on_event = 'InsertCharPre'
build = ':UpdateRemotePlugins'
depends = ['neosnippet.vim']
hook_source = '''
    let g:deoplete#enable_at_startup = 1
    source ~/.vim/rc/plugins/deoplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets']
hook_source = '''
" Plugin key-mappings.
" Note: It must be "imap" and "smap".  It uses <Plug> mappings.
imap <C-k>     <Plug>(neosnippet_expand_or_jump)
smap <C-k>     <Plug>(neosnippet_expand_or_jump)
xmap <C-k>     <Plug>(neosnippet_expand_target)

" SuperTab like snippets behavior.
" Note: It must be "imap" and "smap".  It uses <Plug> mappings.
"imap <expr><TAB>
" \ pumvisible() ? "\<C-n>" :
" \ neosnippet#expandable_or_jumpable() ?
" \    "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
\ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"

" For conceal markers.
if has('conceal')
  set conceallevel=2 concealcursor=niv
endif
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/denite.nvim'
if = "has('nvim')"
on_cmd = 'Denite'
depends = ['neomru.vim', 'neoinclude.vim', 'denite-lab']
build = ':UpdateRemotePlugins'
hook_source = 'source ~/.vim/rc/plugins/denite.rc.vim'
hook_add = '''
    " Prefix key
    nmap [denite] <Nop>
    map <C-j> [denite]

    " Keymap
    " Current direcotry files
    nnoremap <silent> [denite]<C-p> :<C-u>Denite file_rec -highlight-mode-insert=Search<CR>
    " Buffer files
    nnoremap <silent> [denite]<C-b> :<C-u>Denite buffer -highlight-mode-insert=Search<CR>
    " Outline current file
    nnoremap <silent> [denite]<C-o> :<C-u>Denite outline -highlight-mode-insert=Search<CR>
    " Reccent file
    nnoremap <silent> [denite]<C-r> :<C-u>Denite file_mru -highlight-mode-insert=Search<CR>
    " Help tag
    nnoremap <silent> [denite]<C-h> :<C-u>Denite help -highlight-mode-insert=Search<CR>
'''

[[plugins]]
repo = 'lighttiger2505/denite-lab'
hook_add = '''
    nnoremap <silent> [denite]<C-i> :<C-u>Denite lab_issue -highlight-mode-insert=Search<CR>
    nnoremap <silent> [denite]<C-m> :<C-u>Denite lab_merge_request -highlight-mode-insert=Search<CR>
'''


[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoinclude.vim'

# [[plugins]]
# repo = 'kassio/neoterm'
# on_cmd = 'T'
# on_ft = ['python']
# if = "has('nvim')"
# hook_add = '''
# " escape on terminal mode
# tnoremap <silent> <ESC> <C-\><C-n>
# " launch tig on terminal emurater
# nnoremap <silent> <Leader>tg :T tig status<CR>
# " repl on terminal
# nnoremap <silent> <Leader>tl :TREPLSendLine<CR>
# nnoremap <silent> <Leader>tv :TREPLSendSelection<CR>
# '''
# hook_source = '''
# " neoterm options
# let g:neoterm_autojump = 1
# let g:neoterm_autoinsert = 1
# let g:neoterm_autoscroll = 1
# let g:neoterm_keep_term_open = 0
# " let g:neoterm_position = 'horizontal'
# '''

[[plugins]]
repo = 'zchee/deoplete-clang'
on_ft = ['c', 'h']
depends = ['deoplete.nvim']

[[plugins]]
repo = 'zchee/deoplete-zsh'
on_ft = ['zsh']
depends = ['deoplete.nvim']

repo = 'Shougo/neco-vim'
on_ft = ['vim']
depends = ['deoplete.nvim']
