
# tap repositories and their packages

tap homebrew/core
brew gdbm
brew libyaml
brew mas
brew openssl
brew perl
brew python
brew readline
brew ruby
brew sqlite
brew vim
brew xz

tap caskroom/cask

tap rcmdnk/file
brew brew-file

# App Store applications
appstore 682658836 GarageBand (10.2.0)
appstore 408981434 iMovie (10.1.8)
appstore 409183694 Keynote (7.3.1)
appstore 409203825 Numbers (4.3.1)
appstore 409201541 Pages (6.3.1)
