cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "caskroom/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"

brew "docker"
brew "exa"
brew "fd"
brew "fzf"
brew "ghq"
brew "gibo"
brew "hub"
brew "jq"
brew "ripgrep"
brew "tig"
brew "tmux"
brew "neovim"
brew "massren"
brew "zsh"
brew "zplug"

cask "bitwarden"
cask "docker"
cask "font-powerline-symbols"
cask "google-chrome"
cask "iterm2"
cask "jetbrains-toolbox"
cask "karabiner-elements"
