cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"

brew "docker"
brew "exa"
brew "fd"
brew "fzf"
brew "ghq"
brew "gibo"
brew "hub"
brew "jq"
brew "ripgrep"
brew "tig"
brew "tmux"
brew "neovim"
brew "node"
brew "massren"
brew "zsh"

cask "alacritty"
cask "docker"
cask "font-fira-code"
cask "google-chrome"
cask "jetbrains-toolbox"
cask "karabiner-elements"
cask "visual-studio-code"
