#!/usr/local/bin/zsh

# ------------------------------------
# General
# ------------------------------------

export EDITOR='nvim'
export LANG=ja_JP.UTF-8
export XDG_CONFIG_HOME="$HOME/.config"

# ignore /etc/zshrc
setopt no_global_rcs  

typeset -U path fpath

path=(
  ~/.local/bin
  /usr/local/bin
  ~/bin
  $path
)

fpath=(
  /usr/local/share/zsh/functions
  $fpath
)


# ------------------------------------
# Language Specific
# ------------------------------------

# Go
export GOPATH="${HOME}/go"
path=($GOPATH/bin $path)

# Python
path=(~/.pyenv/shims ~/.pyenv/bin ~/.poetry/bin $path)

# Rust
path=(~/.cargo/bin $path)

# Nim
path=(~/.nimble/bin $path)

