#!/usr/local/bin/zsh

# 色を使用出来るようにする
autoload -Uz colors
colors

setopt auto_pushd
setopt pushd_ignore_dups
setopt extended_glob
setopt auto_cd

# pyenv init
if [ -e ~/.pyenv ]; then
    eval "$(pyenv init -)"
fi

# rbenv init
if [ -e ~/.rbenv ]; then
    eval "$(rbenv init -)"
fi


# load settings
source ~/.zsh/zinit.zsh
source ~/.zsh/prompt.zsh
source ~/.zsh/alias.zsh
source ~/.zsh/keybind.zsh
source ~/.zsh/fzf.zsh

case ${OSTYPE} in
    darwin*)
        source ~/.zshrc.osx
        ;;
    linux*)
        source ~/.zshrc.linux
        ;;
esac

# auto zcompile
if [ ~/.zshrc -nt ~/.zshrc.zwc ]; then
   zcompile ~/.zshrc
fi

# tmux auto start
if [ -x "$(command -v tmux)" ]; then
  # get the IDs
  ID="`tmux list-sessions`"
  if [[ -z "$ID" ]]; then
    tmux new-session
  fi
  create_new_session="Create New Session"
  ID="$ID\n${create_new_session}:"
  ID="`echo $ID | $PERCOL | cut -d: -f1`"
  if [[ "$ID" = "${create_new_session}" ]]; then
    tmux new-session
  elif [[ -n "$ID" ]]; then
    tmux attach-session -t "$ID"
  else
    :  # Start terminal normally
  fi
fi
