#!/usr/local/bin/zsh

# ------------------------------------
# General
# ------------------------------------
export EDITOR='nvim'
export FPATH="$/usr/local/share/zsh/functions:$FPATH"
export LANG=ja_JP.UTF-8
export PATH="${HOME}/.local/bin:/usr/local/bin:${HOME}/bin:$PATH"
export XDG_CONFIG_HOME="$HOME/.config"

# ------------------------------------
# Language Specific
# ------------------------------------

# Go
export GOPATH="${HOME}/go"
export PATH="$GOPATH/bin:$PATH"

# Python
export PIPENV_VENV_IN_PROJECT=true
export PYENV_ROOT="${HOME}/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
export PATH="${HOME}/.poetry/bin:$PATH"

# Rust
export PATH="${HOME}/.cargo/bin:$PATH"

# Nim
export PATH="${HOME}/.nimble/bin:$PATH"
