return {
    {
        "nvim-treesitter/nvim-treesitter",
        opts = {
            highlight = { enable = true },
            ensure_installed = {
                "bash",
                "c",
                "cpp",
                "css",
                "diff",
                "gitignore",
                "go",
                "html",
                "http",
                "java",
                "javascript",
                "json",
                "kotlin",
                "lua",
                "markdown",
                "nix",
                "php",
                "python",
                "query",
                "regex",
                "rust",
                "scss",
                "sql",
                "toml",
                "typescript",
                "vim",
                "yaml",
            },
        },
    },
}
