alias jb='jupyter notebook'
alias jpl='jupyter lab'
alias sp3='~/.pyenv/shims/spyder3'
alias vi='nvim'
alias la='ls -a'
alias ...='cd ../..'
alias ....='cd ../../..'
alias ls='ls -G'
alias rm='rm -i'
alias mv='mv -i'
alias gs='git status'

