# tap repositories and their packages

tap homebrew/core
brew bash-completion
brew coreutils
brew cowsay
brew curl
brew fortune
brew git
brew openssl
brew peco
brew pipenv
brew pyenv
brew nvim
brew wget
brew fzf
brew zplug
brew zsh

tap caskroom/cask
cask slack
cask sourcetree

tap rcmdnk/file
brew brew-file
