name: check chezmoi applying

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.platform }}
    steps:

    - uses: actions/checkout@v2
    - name: Cache Brewfile
      uses: actions/cache@v1
      id: brewfile
      with:
        path: Brewfile
        key: poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          poetry-${{ hashFiles('**/poetry.lock') }}
    - name: Set Poetry config
      run: |
        poetry config virtualenvs.in-project false
        poetry config virtualenvs.path ~/.virtualenvs
    - name: Install Dependencies
      run: poetry install -vv
      if: steps.cache.outputs.cache-hit != 'true'

      - run: curl -sfL https://git.io/chezmoi | sh && sudo cp ./bin/chezmoi /usr/local/bin/chezmoi
      - run: chezmoi init https://github.com/kitagawa-hr/dotfiles.git
      